<?php

declare(strict_types=1);

/*
 * This file is part of the pseudify database pseudonymizer project
 * - (c) 2025 waldhacker UG (haftungsbeschränkt)
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

namespace Waldhacker\Pseudify\Core\Processor\Processing;

class DataProcessing implements DataProcessingInterface
{
    private readonly string $identifier;

    /**
     * @api
     */
    public function __construct(
        private readonly \Closure $processor,
        ?string $identifier = null,
    ) {
        $this->identifier = $identifier ?? 'autogenerated-'.uniqid();
    }

    /**
     * @internal
     */
    #[\Override]
    public function getIdentifier(): string
    {
        return $this->identifier;
    }

    /**
     * @internal
     */
    #[\Override]
    public function getProcessor(): callable
    {
        return $this->processor;
    }
}
